Revert "frameworks: Add support for clock auto-hiding"
This reverts commit 703986fd5b7e6549cdaff662c06a7ae526c46ddb.

* Fixes the following error, caused by a merge conflict being resolved
  incorrectly at
  packages/SystemUI/src/com/android/systemui/statusbar/policy/Clock.java

```
error: /home/windowzytch/releases/kasumi/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/Clock.java:98: error: cannot find symbol
    private TaskStackListenerImpl mTaskStackListener = null;
            ^
  symbol:   class TaskStackListenerImpl
  location: class Clock
```

  The conflict happened because we already had this feature controlled
  by a receiver Trebuchet (ig?) provides.

Signed-off-by: Beru Shinsetsu <windowz414@1337.lgbt>